---
- name: ensure PPA repos addition supported
  apt: pkg={{ item }} state=present
  with_items:
    - python-apt
    - python-pycurl
  sudo: yes

- name: ensure cURL main repo.
  apt_repository: repo='ppa:costamagnagianfranco/ettercap-stable-backports' state=present
  when: ansible_lsb.codename == 'precise' or ansible_lsb.codename == 'luna'
  tags:
    - plowshare
  sudo: yes

- name: ensure package archive up-to-date
  apt: update_cache=yes
  when: ansible_lsb.codename == 'precise' or ansible_lsb.codename == 'luna'
  tags:
    - plowshare
  sudo: yes

- name: ensure packages available
  apt: pkg=curl state=latest
  when: ansible_lsb.codename == 'precise' or ansible_lsb.codename == 'luna'
  tags:
    - plowshare
  sudo: yes

- name: ensure repo available
  apt_repository: repo='ppa:plowsharepackagers/ppa'
  tags:
    - plowshare
  sudo: yes

- name: Ensure packages available
  apt: pkg=plowshare state=present install_recommends=no
  tags:
    - plowshare
  sudo: yes

- name: ensure sane Plowshare conf.
  copy: src=../files/plowshare.conf dest=~/.config/plowshare/
  tags:
    - plowshare
